version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      DB_HOST: host.docker.internal  # Connect to the host machine's MySQL
      DB_USER: root
      DB_PASSWORD: Aarthi@123
      DB_NAME: employee_details
    networks:
      - my_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge